import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def to_lines(s):
    return s.splitlines(keepends=True)

# ── Fix 1: layer-trials.ipynb cell 64 ─────────────────────────────────────────
with open('layer-trials.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

cell64_new = (
'# Bootstrap analysis (paired bootstrap over prompt pairs)\n'
'import json\n'
'import numpy as np\n'
'\n'
'def paired_bootstrap_summary(baseline_per_prompt, pruned_per_prompt, metric_key, n_boot=5000, seed=0):\n'
'    """Paired bootstrap test. baseline/pruned are lists of per-prompt metric dicts."""\n'
'    rng    = np.random.default_rng(seed)\n'
'    base   = np.array([d[metric_key] for d in baseline_per_prompt])\n'
'    pruned = np.array([d[metric_key] for d in pruned_per_prompt])\n'
'    diffs  = pruned - base\n'
'    n      = len(diffs)\n'
'    boots  = np.array([rng.choice(diffs, n).mean() for _ in range(n_boot)])\n'
'    ci     = np.percentile(boots, [2.5, 97.5])\n'
'    mean   = boots.mean()\n'
'    pval   = 2 * min((boots >= 0).mean(), (boots <= 0).mean())\n'
'    return {"mean_diff": float(mean), "ci": [float(ci[0]), float(ci[1])], "pval": float(pval)}\n'
'\n'
'print("paired_bootstrap_summary defined.")\n'
'print(\'Usage: result = paired_bootstrap_summary(baseline_data, pruned_data, "cf_tvd")\')\n'
'print(\'       print(result)  # mean_diff, 95% CI, p-value\')\n'
'\n'
'# Quick demo using existing TinyLlama analysis results\n'
'if "analysis_results_tinyllama" in dir() and analysis_results_tinyllama:\n'
'    print()\n'
'    print("Demo: bootstrap over TinyLlama pll_stereotype (per-ablation)")\n'
'    bsl = analysis_results_tinyllama["baseline"]\n'
'    # run_full_evaluation() stores raw PLL as "pll_stereotype_raw"; ablation rows use "pll_stereotype_score"\n'
'    bsl_val = bsl.get("pll_stereotype_raw", bsl.get("pll_stereotype_score", 0.5))\n'
'    pruned_vals = [r["pll_stereotype_score"]\n'
'                   for r in analysis_results_tinyllama["ablation_results"]]\n'
'    base_list   = [{"pll_stereotype_score": bsl_val}] * len(pruned_vals)\n'
'    pruned_list = [{"pll_stereotype_score": v} for v in pruned_vals]\n'
'    r = paired_bootstrap_summary(base_list, pruned_list, "pll_stereotype_score")\n'
'    md, ci0, ci1, pv = r["mean_diff"], r["ci"][0], r["ci"][1], r["pval"]\n'
'    print(f"  mean_diff={md:+.4f}  95%CI=[{ci0:+.4f}, {ci1:+.4f}]  p={pv:.4f}")\n'
)

nb['cells'][64]['source'] = to_lines(cell64_new)
nb['cells'][64]['cell_type'] = 'code'
nb['cells'][64]['outputs'] = []

try:
    compile(cell64_new, '<cell64>', 'exec')
    print('layer-trials cell 64: OK')
except SyntaxError as e:
    print(f'layer-trials cell 64: SyntaxError line {e.lineno}: {e.msg}')

with open('layer-trials.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('layer-trials.ipynb saved.')

# ── Fix 2: mistral.ipynb cell 32 ──────────────────────────────────────────────
with open('mistral.ipynb', 'r', encoding='utf-8') as f:
    nb2 = json.load(f)

cell32_new = (
'# ═══════════════════════════════════════════════════════════════════════\n'
'# OFFLINE REVIEWER TESTS — runs all 4 comparison tests from saved data\n'
'# No model reload required. Run this after the parser cell above.\n'
'# ═══════════════════════════════════════════════════════════════════════\n'
'import json\n'
'\n'
'if not _results_map:\n'
'    print("⚠  Run the parser cell first.")\n'
'else:\n'
'    # ── TEST 1: TVD=0 Validation (R2 concern #3) ──────────────────────\n'
'    print("\\n" + "═"*65)\n'
'    print("  TEST 1 — TVD=0.0000 Validation")\n'
'    print("═"*65)\n'
'    for model_name, results in _results_map.items():\n'
'        baseline_tvd = results["baseline"]["counterfactual_tvd"]\n'
'        ablations = results["ablation_results"]\n'
'        print(f"\\n  {model_name}  (baseline TVD={baseline_tvd:.4f})")\n'
'        print(f"  {\'Layer\':<8} {\'TVD\':>8} {\'Δ\':>8} {\'PPL ratio\':>10} {\'Accepted\':>10}")\n'
'        print("  " + "-"*48)\n'
'        zero_layers = []\n'
'        for r in sorted(ablations, key=lambda x: x["layer_removed"]):\n'
'            tvd = r["counterfactual_tvd"]\n'
'            flag = " ← ZERO" if tvd < 0.001 else ""\n'
'            if tvd < 0.001:\n'
'                zero_layers.append(r["layer_removed"])\n'
'            if r["accepted"] or tvd < 0.001:\n'
'                print(f"  L{r[\'layer_removed\']:<6} {tvd:>8.4f} {tvd-baseline_tvd:>+8.4f} "\n'
'                      f"{r[\'ppl_ratio\']:>10.3f} {str(r[\'accepted\']):>10}{flag}")\n'
'        if zero_layers:\n'
'            print(f"\\n  ⚠ TVD≈0 layers: {zero_layers}")\n'
'        else:\n'
'            print(f"\\n  ✓ No TVD≈0 issues found.")\n'
'\n'
'    # ── TEST 2: Metric Summary Table (R2 concern #2 — sensitivity proxy) ──\n'
'    print("\\n\\n" + "═"*65)\n'
'    print("  TEST 2 — Bias Metric Summary per Model (α=1.0, β=0.5, γ=1.5)")\n'
'    print("═"*65)\n'
'    summary_rows = []\n'
'    for model_name, results in _results_map.items():\n'
'        bsl = results["baseline"]\n'
'        cands = results["recommended_pruning_candidates"]\n'
'        if not cands:\n'
'            continue\n'
'        best_layer = cands[0]\n'
'        best = next((a for a in results["ablation_results"]\n'
'                     if a["layer_removed"] == best_layer), None)\n'
'        if best is None:\n'
'            continue\n'
'        row = {\n'
'            "model": model_name,\n'
'            "best_layer": best_layer,\n'
'            "ppl_ratio": best["ppl_ratio"],\n'
'            "Δpll_raw": best["pll_stereotype_score"] - bsl["pll_stereotype_score"],\n'
'            "Δcf_tvd":  best["counterfactual_tvd"]   - bsl["counterfactual_tvd"],\n'
'            "Δtoxic":   best["toxicity_propensity"]   - bsl["toxicity_propensity"],\n'
'            "accepted":  best["accepted"],\n'
'            "n_improved": best["fairness_improvements"],\n'
'        }\n'
'        summary_rows.append(row)\n'
'\n'
'    print(f"\\n  {\'Model\':<24} {\'Best L\':>7} {\'PPL ratio\':>10} "\n'
'          f"{\'Δpll_raw\':>10} {\'Δcf_tvd\':>10} {\'Δtoxic\':>9} {\'Acc\':>5}")\n'
'    print("  " + "-"*78)\n'
'    for r in summary_rows:\n'
'        print(f"  {r[\'model\']:<24} L{r[\'best_layer\']:<5} {r[\'ppl_ratio\']:>10.3f} "\n'
'              f"{r[\'Δpll_raw\']:>+10.4f} {r[\'Δcf_tvd\']:>+10.4f} {r[\'Δtoxic\']:>+9.4f} "\n'
'              f"{\'✓\' if r[\'accepted\'] else \'✗\':>5}")\n'
'\n'
'    print("\\n--- metric_summary_big (copy-paste) ---")\n'
'    print(json.dumps(summary_rows, indent=2, default=str))\n'
'\n'
'    # ── TEST 3: Baseline Comparisons (R2 concern #6) ──────────────────\n'
'    print("\\n\\n" + "═"*65)\n'
'    print("  TEST 3 — Hybrid vs Baselines (Win Rate over All Ablated Layers)")\n'
'    print("═"*65)\n'
'    baseline_comp_results = {}\n'
'    for model_name, results in _results_map.items():\n'
'        ablations = results["ablation_results"]\n'
'        if not ablations:\n'
'            continue\n'
'        bsl = results["baseline"]\n'
'        hybrid_cand = results["recommended_pruning_candidates"][0] if results["recommended_pruning_candidates"] else None\n'
'        if hybrid_cand is None:\n'
'            continue\n'
'        hybrid_row = next((a for a in ablations if a["layer_removed"] == hybrid_cand), None)\n'
'        if hybrid_row is None:\n'
'            continue\n'
'\n'
'        # Random baseline: average over all non-protected ablations\n'
'        prot = results.get("protected_layers", [0, len(results["hybrid_scores"])-1])\n'
'        non_protected = [a for a in ablations if a["layer_removed"] not in prot]\n'
'        if not non_protected:\n'
'            continue\n'
'        avg_tvd_reduction = float(np.mean(\n'
'            [bsl["counterfactual_tvd"] - a["counterfactual_tvd"] for a in non_protected]))\n'
'        hybrid_tvd_reduction = bsl["counterfactual_tvd"] - hybrid_row["counterfactual_tvd"]\n'
'\n'
'        # Utility-only: layer with smallest ppl_ratio increase\n'
'        utility_layer = min(non_protected, key=lambda a: a["ppl_ratio"])\n'
'        utility_tvd_reduction = bsl["counterfactual_tvd"] - utility_layer["counterfactual_tvd"]\n'
'\n'
'        # Bias-only: layer with largest cf_tvd reduction\n'
'        bias_layer = min(non_protected, key=lambda a: a["counterfactual_tvd"])\n'
'        bias_tvd_reduction = bsl["counterfactual_tvd"] - bias_layer["counterfactual_tvd"]\n'
'\n'
'        print(f"\\n  {model_name}:")\n'
'        print(f"    Hybrid    (L{hybrid_cand}):        TVD Δ={hybrid_tvd_reduction:+.4f}  PPL ratio={hybrid_row[\'ppl_ratio\']:.3f}")\n'
'        print(f"    Utility-only (L{utility_layer[\'layer_removed\']}):   TVD Δ={utility_tvd_reduction:+.4f}  PPL ratio={utility_layer[\'ppl_ratio\']:.3f}")\n'
'        print(f"    Bias-only    (L{bias_layer[\'layer_removed\']}):   TVD Δ={bias_tvd_reduction:+.4f}  PPL ratio={bias_layer[\'ppl_ratio\']:.3f}")\n'
'        print(f"    Random avg:               TVD Δ={avg_tvd_reduction:+.4f}")\n'
'        print(f"    → Hybrid {\'BEST\' if hybrid_tvd_reduction >= bias_tvd_reduction else \'not best\'} at bias reduction  |  "\n'
'              f"{\'BEST\' if hybrid_row[\'ppl_ratio\'] <= utility_layer[\'ppl_ratio\'] else \'more conservative\'} at utility")\n'
'\n'
'        baseline_comp_results[model_name] = {\n'
'            "hybrid": {"layer": hybrid_cand, "tvd_reduction": hybrid_tvd_reduction,\n'
'                       "ppl_ratio": hybrid_row["ppl_ratio"]},\n'
'            "utility_only": {"layer": utility_layer["layer_removed"],\n'
'                             "tvd_reduction": utility_tvd_reduction,\n'
'                             "ppl_ratio": utility_layer["ppl_ratio"]},\n'
'            "bias_only": {"layer": bias_layer["layer_removed"],\n'
'                          "tvd_reduction": bias_tvd_reduction,\n'
'                          "ppl_ratio": bias_layer["ppl_ratio"]},\n'
'            "random_avg_tvd_reduction": avg_tvd_reduction,\n'
'        }\n'
'\n'
'    print("\\n--- baseline_comparisons_offline (copy-paste) ---")\n'
'    print(json.dumps(baseline_comp_results, indent=2, default=str))\n'
'\n'
'    # ── TEST 4: Layer-wise metric table (R2 concern #4 — per-model) ───\n'
'    print("\\n\\n" + "═"*65)\n'
'    print("  TEST 4 — Full Per-Layer Metric Table (all ablated layers)")\n'
'    print("═"*65)\n'
'    all_layer_data = {}\n'
'    for model_name, results in _results_map.items():\n'
'        bsl = results["baseline"]\n'
'        rows = []\n'
'        for a in sorted(results["ablation_results"], key=lambda x: x["layer_removed"]):\n'
'            rows.append({\n'
'                "layer": a["layer_removed"],\n'
'                "pll_raw":   a["pll_stereotype_score"],\n'
'                "pll_corr":  a["pll_stereotype_corrected"],\n'
'                "cf_tvd":    a["counterfactual_tvd"],\n'
'                "toxic":     a["toxicity_propensity"],\n'
'                "ppl":       a["perplexity_neutral"],\n'
'                "ppl_ratio": a["ppl_ratio"],\n'
'                "accepted":  a["accepted"],\n'
'                "n_improved": a["fairness_improvements"],\n'
'            })\n'
'        all_layer_data[model_name] = {"baseline": bsl, "layers": rows}\n'
'        n_acc = sum(1 for r in rows if r["accepted"])\n'
'        best = min(rows, key=lambda x: x["cf_tvd"]) if rows else None\n'
'        if best:\n'
'            print(f"\\n  {model_name}: {len(rows)} layers, {n_acc} accepted, "\n'
'                  f"best TVD L{best[\'layer\']} ({best[\'cf_tvd\']:.4f})")\n'
'        else:\n'
'            print(f"\\n  {model_name}: no data")\n'
'\n'
'    print("\\n--- layer_metrics_big (copy-paste) ---")\n'
'    print(json.dumps(all_layer_data, indent=2, default=str))\n'
'\n'
'    print("\\n\\nAll offline reviewer tests complete.")\n'
)

nb2['cells'][32]['source'] = to_lines(cell32_new)
nb2['cells'][32]['cell_type'] = 'code'
nb2['cells'][32]['outputs'] = []

try:
    compile(cell32_new, '<cell32>', 'exec')
    print('mistral cell 32: OK')
except SyntaxError as e:
    print(f'mistral cell 32: SyntaxError line {e.lineno}: {e.msg}')

with open('mistral.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb2, f, ensure_ascii=False, indent=1)
print('mistral.ipynb saved.')
