import json, sys
sys.stdout.reconfigure(encoding='utf-8')

def to_lines(s):
    return s.splitlines(keepends=True)

with open('layer-trials.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# ── Cell 31: fix validate_zero_tvd keys + add _normalize_results ─────────────
cell31_new = (
'# TVD = 0.0000 validation — addresses R2 concern #3\n'
'\n'
'def _normalize_results(results):\n'
'    """Add derived keys that downstream cells expect.\n'
'    run_full_evaluation() uses pll_stereotype_raw / perplexity_neutral;\n'
'    reviewer cells expect pll_stereotype_score / ppl_ratio / accepted / fairness_improvements.\n'
'    """\n'
'    bsl = results["baseline"]\n'
'    bsl_ppl = bsl.get("perplexity_neutral", 1.0)\n'
'    bsl_tvd = bsl.get("counterfactual_tvd", 0.0)\n'
'\n'
'    if "pll_stereotype_score" not in bsl:\n'
'        bsl["pll_stereotype_score"] = bsl.get("pll_stereotype_raw", 0.5)\n'
'\n'
'    for r in results.get("ablation_results", []):\n'
'        if "ppl_ratio" not in r:\n'
'            r_ppl = r.get("perplexity_neutral", bsl_ppl)\n'
'            r["ppl_ratio"] = r_ppl / bsl_ppl if bsl_ppl > 0 else 1.0\n'
'        if "pll_stereotype_score" not in r:\n'
'            r["pll_stereotype_score"] = r.get("pll_stereotype_raw", 0.5)\n'
'        if "accepted" not in r:\n'
'            tvd = r.get("counterfactual_tvd", bsl_tvd)\n'
'            r["accepted"] = (r["ppl_ratio"] < 1.2) and (tvd <= bsl_tvd)\n'
'        if "fairness_improvements" not in r:\n'
'            n = 0\n'
'            for k in ["pll_stereotype_raw", "counterfactual_tvd",\n'
'                      "toxicity_propensity", "demographic_parity_gap"]:\n'
'                bv, rv = bsl.get(k), r.get(k)\n'
'                if bv is not None and rv is not None and rv < bv:\n'
'                    n += 1\n'
'            r["fairness_improvements"] = n\n'
'    return results\n'
'\n'
'\n'
'def validate_zero_tvd(analysis_results, model_name, threshold=0.001):\n'
'    baseline_tvd = analysis_results["baseline"].get("counterfactual_tvd", None)\n'
'    ablations    = analysis_results.get("ablation_results", [])\n'
'\n'
'    print(f"\\n{model_name} — TVD validation (baseline TVD={baseline_tvd:.4f})")\n'
'    print(f"{\'Layer\':<8} {\'TVD\':>10} {\'Δ from baseline\':>16} {\'PPL ratio\':>10} {\'Accepted\':>10}")\n'
'    print("-" * 58)\n'
'\n'
'    zero_layers = []\n'
'    for r in ablations:\n'
'        tvd = r.get("counterfactual_tvd", None)\n'
'        if tvd is None:\n'
'            continue\n'
'        delta  = tvd - baseline_tvd\n'
'        ppl_r  = r.get("ppl_ratio", float("nan"))\n'
'        accept = r.get("accepted", False)\n'
'        lid    = r.get("layer_removed", r.get("layer_idx", "?"))\n'
'        if tvd < threshold:\n'
'            zero_layers.append(lid)\n'
'            flag = " ← ZERO"\n'
'        else:\n'
'            flag = ""\n'
'        if accept or tvd < threshold:\n'
'            print(f"  L{lid:<5} {tvd:>10.6f} {delta:>+16.4f} {ppl_r:>10.3f} {str(accept):>10}{flag}")\n'
'\n'
'    if zero_layers:\n'
'        print(f"\\n⚠ Layers with TVD≈0: {zero_layers}")\n'
'        print("Mechanistic explanation: these layers are the primary source of")\n'
'        print("demographic-token probability differentiation. Removing them collapses")\n'
'        print("the model\'s pronoun distribution to near-uniform, yielding TVD≈0.")\n'
'        print("Verify this is not a numerical artifact by checking raw logit differences.")\n'
'    else:\n'
'        print("\\n✓ No TVD≈0 results found — no validation issue.")\n'
'\n'
'    return zero_layers\n'
'\n'
'\n'
'# Build _results_map from whatever analysis results are available\n'
'_results_map = {}\n'
'for _name, _var in [("tinyllama", "analysis_results_tinyllama"),\n'
'                     ("qwen",      "analysis_results_qwen")]:\n'
'    if _var in dir() and eval(_var) is not None:\n'
'        _results_map[_name] = _normalize_results(eval(_var))\n'
'\n'
'if not _results_map:\n'
'    print("⚠  No analysis results found — run the TinyLlama / Qwen analysis cells first.")\n'
'else:\n'
'    print(f"✓ _results_map built: {list(_results_map.keys())}")\n'
'    print(f"  Normalized keys added: ppl_ratio, pll_stereotype_score, accepted, fairness_improvements")\n'
'    for _name, _res in _results_map.items():\n'
'        validate_zero_tvd(_res, _name)\n'
)

# ── Cell 64: fix ablation row key (baseline already fixed) ────────────────────
cell64_new = (
'# Bootstrap analysis (paired bootstrap over prompt pairs)\n'
'import json\n'
'import numpy as np\n'
'\n'
'def paired_bootstrap_summary(baseline_per_prompt, pruned_per_prompt, metric_key, n_boot=5000, seed=0):\n'
'    """Paired bootstrap test. baseline/pruned are lists of per-prompt metric dicts."""\n'
'    rng    = np.random.default_rng(seed)\n'
'    base   = np.array([d[metric_key] for d in baseline_per_prompt])\n'
'    pruned = np.array([d[metric_key] for d in pruned_per_prompt])\n'
'    diffs  = pruned - base\n'
'    n      = len(diffs)\n'
'    boots  = np.array([rng.choice(diffs, n).mean() for _ in range(n_boot)])\n'
'    ci     = np.percentile(boots, [2.5, 97.5])\n'
'    mean   = boots.mean()\n'
'    pval   = 2 * min((boots >= 0).mean(), (boots <= 0).mean())\n'
'    return {"mean_diff": float(mean), "ci": [float(ci[0]), float(ci[1])], "pval": float(pval)}\n'
'\n'
'print("paired_bootstrap_summary defined.")\n'
'print(\'Usage: result = paired_bootstrap_summary(baseline_data, pruned_data, "cf_tvd")\')\n'
'print(\'       print(result)  # mean_diff, 95% CI, p-value\')\n'
'\n'
'# Quick demo using existing TinyLlama analysis results\n'
'if "analysis_results_tinyllama" in dir() and analysis_results_tinyllama:\n'
'    print()\n'
'    print("Demo: bootstrap over TinyLlama pll_stereotype (per-ablation)")\n'
'    bsl = analysis_results_tinyllama["baseline"]\n'
'    bsl_val = bsl.get("pll_stereotype_raw", bsl.get("pll_stereotype_score", 0.5))\n'
'    pruned_vals = [r.get("pll_stereotype_raw", r.get("pll_stereotype_score", 0.5))\n'
'                   for r in analysis_results_tinyllama["ablation_results"]]\n'
'    base_list   = [{"pll": bsl_val}] * len(pruned_vals)\n'
'    pruned_list = [{"pll": v} for v in pruned_vals]\n'
'    r = paired_bootstrap_summary(base_list, pruned_list, "pll")\n'
'    md, ci0, ci1, pv = r["mean_diff"], r["ci"][0], r["ci"][1], r["pval"]\n'
'    print(f"  mean_diff={md:+.4f}  95%CI=[{ci0:+.4f}, {ci1:+.4f}]  p={pv:.4f}")\n'
)

# ── Cell 65: fix ppl_ratio and pll_stereotype_score ───────────────────────────
cell65_new = (
'# Sensitivity sweep for hybrid weights (alpha, beta, gamma)\n'
'# Uses per-layer ablation metrics from analysis_results -- no file I/O.\n'
'import json, itertools\n'
'import numpy as np\n'
'\n'
'def run_hybrid_sensitivity(analysis_results, model_name="model"):\n'
'    ablations = analysis_results.get("ablation_results", [])\n'
'    if not ablations:\n'
'        print("No ablation results."); return\n'
'    bsl       = analysis_results["baseline"]\n'
'    bsl_ppl   = bsl.get("perplexity_neutral", 1.0)\n'
'    bsl_pll   = bsl.get("pll_stereotype_raw", bsl.get("pll_stereotype_score", 0.5))\n'
'    layer_ids = [r["layer_removed"] for r in ablations]\n'
'\n'
'    # ppl_ratio: use stored key if present, else compute from perplexity_neutral\n'
'    ppl_ratios = np.array([\n'
'        r.get("ppl_ratio",\n'
'              r.get("perplexity_neutral", bsl_ppl) / bsl_ppl if bsl_ppl > 0 else 1.0)\n'
'        for r in ablations\n'
'    ])\n'
'    utility    = 1.0 - np.clip(ppl_ratios - 1.0, 0, 1)\n'
'    redundancy = np.full(len(ablations), 0.5)\n'
'    bias       = np.array([\n'
'        r.get("pll_stereotype_raw", r.get("pll_stereotype_score", 0.5))\n'
'        for r in ablations\n'
'    ])\n'
'\n'
'    alphas = [0.5, 1.0, 1.5]\n'
'    betas  = [0.0, 0.5, 1.0]\n'
'    gammas = [0.5, 1.5, 2.5]\n'
'    print(f"Hybrid weight sensitivity sweep -- {model_name}")\n'
'    print(f"  {len(layer_ids)} layers | baseline pll_stereotype_raw={bsl_pll:.4f}")\n'
'    print()\n'
'    print(f"  {\'alpha\':>6} {\'beta\':>6} {\'gamma\':>6}  top-3 candidates")\n'
'    print("  " + "-"*50)\n'
'    rows = []\n'
'    for a, b, g in itertools.product(alphas, betas, gammas):\n'
'        raw  = a * utility + b * redundancy - g * bias\n'
'        mn, mx = raw.min(), raw.max()\n'
'        norm = (raw - mn) / (mx - mn + 1e-9)\n'
'        top3_idx = np.argsort(norm)[-3:][::-1]\n'
'        top3 = [layer_ids[i] for i in top3_idx]\n'
'        rows.append({"alpha": a, "beta": b, "gamma": g, "top3": top3})\n'
'        print(f"  {a:6.1f} {b:6.1f} {g:6.1f}  L{top3[0]}, L{top3[1]}, L{top3[2]}")\n'
'    print()\n'
'    print("--- JSON (copy-paste) ---")\n'
'    print(json.dumps(rows, indent=2))\n'
'    return rows\n'
'\n'
'if "analysis_results_tinyllama" in dir() and analysis_results_tinyllama:\n'
'    run_hybrid_sensitivity(analysis_results_tinyllama, "TinyLlama-1.1B")\n'
'elif "analysis_results_qwen" in dir() and analysis_results_qwen:\n'
'    run_hybrid_sensitivity(analysis_results_qwen, "Qwen2.5-0.5B")\n'
'else:\n'
'    print("Run TinyLlama/Qwen analysis first (cells 28/30), then re-run this cell.")\n'
)

nb['cells'][31]['source'] = to_lines(cell31_new)
nb['cells'][31]['cell_type'] = 'code'
nb['cells'][31]['outputs'] = []

nb['cells'][64]['source'] = to_lines(cell64_new)
nb['cells'][64]['cell_type'] = 'code'
nb['cells'][64]['outputs'] = []

nb['cells'][65]['source'] = to_lines(cell65_new)
nb['cells'][65]['cell_type'] = 'code'
nb['cells'][65]['outputs'] = []

for ci, src in [(31, cell31_new), (64, cell64_new), (65, cell65_new)]:
    try:
        compile(src, f'<cell{ci}>', 'exec')
        print(f'Cell {ci}: OK')
    except SyntaxError as e:
        print(f'Cell {ci}: SyntaxError line {e.lineno}: {e.msg}')
        lines = src.splitlines()
        for ln in range(max(0, e.lineno-3), min(len(lines), e.lineno+2)):
            print(f'  {ln+1}: {repr(lines[ln])}')

with open('layer-trials.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('layer-trials.ipynb saved.')
